name: chefium

description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

  flutter_facebook_login: ^3.0.0
  apple_sign_in: ^0.1.0
  dio: ^3.0.9
  dio_http_cache: ^0.2.6
  firebase_admob: ^0.9.3+2
  firebase_analytics: ^5.0.15
  google_sign_in: ^4.5.1
  shared_preferences: ^0.5.7+3
  animations: ^1.1.1
  flushbar: ^1.10.4
  timeago: ^2.0.26
  photo_view: ^0.9.2
  image_editor_pro: ^1.0.6
  image_editor: ^0.7.1
  flutter_native_admob: ^2.1.0
  circular_profile_avatar: ^1.0.6
  cached_network_image: ^2.2.0+1
  font_awesome_flutter: ^8.8.1
  autocomplete_textfield: ^1.7.3
  intl: ^0.16.1
  fraction: ^1.0.1
  flutter_tags: ^0.4.8+2
  flutter_svg: ^0.17.4
  flag: ^3.0.1
  image_picker: ^0.6.7+2
  implicitly_animated_reorderable_list: ^0.2.3
  extended_image: ^0.9.0
  pull_to_refresh: ^1.6.0
  custom_refresh_indicator: ^0.8.0+1
  flutter_spinkit: ^4.1.2+1
  url_launcher: ^5.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - lib/assets/images/logotipo_amarillo.png
    - lib/assets/images/logotipo.png
    - lib/assets/images/splash.jpg
    - lib/assets/images/login.png
    - lib/assets/images/home.png
  fonts:
    - family: SourceSansPro
      fonts:
        - asset: lib/assets/fonts/SourceSansPro-Regular.ttf
        - asset: lib/assets/fonts/SourceSansPro-Bold.ttf
          weight: 600
        - asset: lib/assets/fonts/SourceSansPro-SemiBold.ttf
          weight: 400
    - family: SourceSerifPro
      fonts:
        - asset: lib/assets/fonts/SourceSerifPro-Regular.ttf
        - asset: lib/assets/fonts/SourceSerifPro-Bold.ttf
          weight: 500
    - family: Chefium
      fonts:
        - asset: lib/assets/fonts/Chefium.ttf
  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
