/// Flutter icons Chefium
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Chefium
///      fonts:
///       - asset: fonts/Chefium.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class ChefiumIcons {
  ChefiumIcons._();

  static const _kFontFam = 'Chefium';
  static const _kFontPkg = null;

  static const IconData up_arrow = IconData(0xe900, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart_outlined = IconData(0xe901, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart = IconData(0xe902, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notification = IconData(0xe903, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData spatula = IconData(0xe904, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData photo = IconData(0xe905, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData no_fruit_seed = IconData(0xe906, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData no_honey = IconData(0xe907, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData no_ice = IconData(0xe908, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData no_wheat = IconData(0xe909, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData no_rice = IconData(0xe90a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData no_egg = IconData(0xe90b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData no_dairy = IconData(0xe90c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wine = IconData(0xe90d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData beer = IconData(0xe90e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cocktail = IconData(0xe90f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData no_beef = IconData(0xe910, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData no_chicken = IconData(0xe911, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData no_fish = IconData(0xe912, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData no_shellfish = IconData(0xe913, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData note = IconData(0xe914, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dish = IconData(0xe915, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chef = IconData(0xe916, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData map = IconData(0xe917, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cross = IconData(0xe918, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search = IconData(0xe919, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData drink = IconData(0xe91a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tea = IconData(0xe91b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ice = IconData(0xe91c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cake = IconData(0xe91d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dessert = IconData(0xe91e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData honey = IconData(0xe91f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData group_30 = IconData(0xe920, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vegetable = IconData(0xe921, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fruit = IconData(0xe922, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fruit_seed = IconData(0xe923, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData seed = IconData(0xe924, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rice = IconData(0xe925, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wheat = IconData(0xe926, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData oil = IconData(0xe927, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gear = IconData(0xe928, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shield = IconData(0xe929, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user = IconData(0xe92a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plus = IconData(0xe92b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData egg = IconData(0xe92c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dairy = IconData(0xe92d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData legume = IconData(0xe92e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shellfish = IconData(0xe92f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fish = IconData(0xe930, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chicken = IconData(0xe931, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData beef = IconData(0xe932, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData left_arrow = IconData(0xe933, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData right_arrow = IconData(0xe934, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData down_arrow = IconData(0xe935, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
